[package]
name = "base64"
version = "0.21.3"
authors = ["Alice Maz <alice@alicemaz.com>", "Marshall Pierce <marshall@mpierce.org>"]
description = "encodes and decodes base64 as bytes or utf8"
repository = "https://github.com/marshallpierce/rust-base64"
documentation = "https://docs.rs/base64"
readme = "README.md"
keywords = ["base64", "utf8", "encode", "decode", "no_std"]
categories = ["encoding"]
license = "MIT OR Apache-2.0"
edition = "2021"
# dev-dependencies require 1.60, but the main code doesn't
# This option was added in 1.56, keep it for when we bump MSRV.
rust-version = "1.56.0"

[[bench]]
name = "benchmarks"
harness = false

[package.metadata.docs.rs]
rustdoc-args = ["--generate-link-to-definition"]

[dev-dependencies]
criterion = "0.4"
# clap 4 would require 1.60
structopt = "0.3"
# test fixtures for engine tests
rstest = "0.12"
rstest_reuse = "0.3"
lazy_static = "1"
rand = { path = "../rand", features = ["small_rng"] }

[features]
default = ["std"]
alloc = []
std = []

[profile.bench]
# Useful for better disassembly when using `perf record` and `perf annotate`
debug = true

[profile.test]
# Faster tests save much more than the increase in compilation time
opt-level = 3
